#pragma once

// From glfw3.h
#define NAGI_MOUSE_BUTTON_1         0
#define NAGI_MOUSE_BUTTON_2         1
#define NAGI_MOUSE_BUTTON_3         2
#define NAGI_MOUSE_BUTTON_4         3
#define NAGI_MOUSE_BUTTON_5         4
#define NAGI_MOUSE_BUTTON_6         5
#define NAGI_MOUSE_BUTTON_7         6
#define NAGI_MOUSE_BUTTON_8         7
#define NAGI_MOUSE_BUTTON_LAST      NAGI_MOUSE_BUTTON_8
#define NAGI_MOUSE_BUTTON_LEFT      NAGI_MOUSE_BUTTON_1
#define NAGI_MOUSE_BUTTON_RIGHT     NAGI_MOUSE_BUTTON_2
#define NAGI_MOUSE_BUTTON_MIDDLE    NAGI_MOUSE_BUTTON_3